/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LaunchDotFunPresale {
  export type PresaleOptionsStruct = {
    tokenPresale: BigNumberish;
    hardCap: BigNumberish;
    softCap: BigNumberish;
    start: BigNumberish;
    end: BigNumberish;
  };

  export type PresaleOptionsStructOutput = [
    tokenPresale: bigint,
    hardCap: bigint,
    softCap: bigint,
    start: bigint,
    end: bigint,
  ] & {
    tokenPresale: bigint;
    hardCap: bigint;
    softCap: bigint;
    start: bigint;
    end: bigint;
  };
}

export interface LaunchDotFunPresaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimTokens"
      | "claimableTokens"
      | "claimed"
      | "confidentialProtocolId"
      | "contributions"
      | "fillDenominator"
      | "fillNumerator"
      | "finalizePreSale"
      | "onERC721Received"
      | "owner"
      | "placeBid"
      | "pool"
      | "refund"
      | "refunded"
      | "renounceOwnership"
      | "settleBid"
      | "settled"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "PoolInitialized"): EventFragment;

  encodeFunctionData(functionFragment: "claimTokens", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "claimableTokens", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "claimed", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "confidentialProtocolId", values?: undefined): string;
  encodeFunctionData(functionFragment: "contributions", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "fillDenominator", values?: undefined): string;
  encodeFunctionData(functionFragment: "fillNumerator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizePreSale",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "placeBid", values: [AddressLike, BytesLike, BytesLike]): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(functionFragment: "refunded", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "renounceOwnership", values?: undefined): string;
  encodeFunctionData(functionFragment: "settleBid", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "settled", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "transferOwnership", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "claimTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimableTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "confidentialProtocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contributions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fillDenominator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fillNumerator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finalizePreSale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onERC721Received", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refunded", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settleBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferOwnership", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolInitializedEvent {
  export type InputTuple = [
    creator: AddressLike,
    amount: BigNumberish,
    liquidityTokens: BigNumberish,
    presaleTokens: BigNumberish,
    timestamp: BigNumberish,
  ];
  export type OutputTuple = [
    creator: string,
    amount: bigint,
    liquidityTokens: bigint,
    presaleTokens: bigint,
    timestamp: bigint,
  ];
  export interface OutputObject {
    creator: string;
    amount: bigint;
    liquidityTokens: bigint;
    presaleTokens: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LaunchDotFunPresale extends BaseContract {
  connect(runner?: ContractRunner | null): LaunchDotFunPresale;
  waitForDeployment(): Promise<this>;

  interface: LaunchDotFunPresaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  claimTokens: TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;

  claimableTokens: TypedContractMethod<[user: AddressLike], [string], "view">;

  claimed: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  contributions: TypedContractMethod<[user: AddressLike], [string], "view">;

  fillDenominator: TypedContractMethod<[], [bigint], "view">;

  fillNumerator: TypedContractMethod<[], [bigint], "view">;

  finalizePreSale: TypedContractMethod<
    [ethRaised: BigNumberish, tokensSold: BigNumberish, _fillNumerator: BigNumberish, _fillDenominator: BigNumberish],
    [void],
    "nonpayable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  placeBid: TypedContractMethod<
    [beneficiary: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  pool: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        LaunchDotFunPresale.PresaleOptionsStructOutput,
      ] & {
        token: string;
        ztoken: string;
        tokenBalance: bigint;
        tokensSold: bigint;
        weiRaised: bigint;
        ethRaisedEncrypted: string;
        tokenPerEthWithDecimals: bigint;
        zweth: string;
        state: bigint;
        options: LaunchDotFunPresale.PresaleOptionsStructOutput;
      },
    ],
    "view"
  >;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  refunded: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settleBid: TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;

  settled: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "claimTokens"): TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "claimableTokens"): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(nameOrSignature: "claimed"): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "confidentialProtocolId"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "contributions"): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(nameOrSignature: "fillDenominator"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "fillNumerator"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizePreSale"
  ): TypedContractMethod<
    [ethRaised: BigNumberish, tokensSold: BigNumberish, _fillNumerator: BigNumberish, _fillDenominator: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<[arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike], [string], "view">;
  getFunction(nameOrSignature: "owner"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [beneficiary: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "pool"): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        LaunchDotFunPresale.PresaleOptionsStructOutput,
      ] & {
        token: string;
        ztoken: string;
        tokenBalance: bigint;
        tokensSold: bigint;
        weiRaised: bigint;
        ethRaisedEncrypted: string;
        tokenPerEthWithDecimals: bigint;
        zweth: string;
        state: bigint;
        options: LaunchDotFunPresale.PresaleOptionsStructOutput;
      },
    ],
    "view"
  >;
  getFunction(nameOrSignature: "refund"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "refunded"): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "renounceOwnership"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "settleBid"): TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "settled"): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(nameOrSignature: "transferOwnership"): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolInitialized"
  ): TypedContractEvent<
    PoolInitializedEvent.InputTuple,
    PoolInitializedEvent.OutputTuple,
    PoolInitializedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolInitialized(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
    PoolInitialized: TypedContractEvent<
      PoolInitializedEvent.InputTuple,
      PoolInitializedEvent.OutputTuple,
      PoolInitializedEvent.OutputObject
    >;
  };
}
