/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LaunchDotFunPresale {
  export type PresaleOptionsStruct = {
    tokenPresale: BigNumberish;
    hardCap: BigNumberish;
    softCap: BigNumberish;
    start: BigNumberish;
    end: BigNumberish;
  };

  export type PresaleOptionsStructOutput = [
    tokenPresale: bigint,
    hardCap: bigint,
    softCap: bigint,
    start: bigint,
    end: bigint,
  ] & {
    tokenPresale: bigint;
    hardCap: bigint;
    softCap: bigint;
    start: bigint;
    end: bigint;
  };
}

export interface LaunchDotFunPresaleFactoryInterface extends Interface {
  getFunction(nameOrSignature: "allPresales" | "createLaunchDotFunPresale" | "getPresalesByCreator"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LaunchDotFunPresaleCreated"): EventFragment;

  encodeFunctionData(functionFragment: "allPresales", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "createLaunchDotFunPresale",
    values: [AddressLike, LaunchDotFunPresale.PresaleOptionsStruct]
  ): string;
  encodeFunctionData(functionFragment: "getPresalesByCreator", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "allPresales", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createLaunchDotFunPresale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPresalesByCreator", data: BytesLike): Result;
}

export namespace LaunchDotFunPresaleCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    presale: AddressLike,
    token: AddressLike,
    ztoken: AddressLike,
    zweth: AddressLike,
  ];
  export type OutputTuple = [creator: string, presale: string, token: string, ztoken: string, zweth: string];
  export interface OutputObject {
    creator: string;
    presale: string;
    token: string;
    ztoken: string;
    zweth: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LaunchDotFunPresaleFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LaunchDotFunPresaleFactory;
  waitForDeployment(): Promise<this>;

  interface: LaunchDotFunPresaleFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  allPresales: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createLaunchDotFunPresale: TypedContractMethod<
    [_token: AddressLike, _options: LaunchDotFunPresale.PresaleOptionsStruct],
    [string],
    "nonpayable"
  >;

  getPresalesByCreator: TypedContractMethod<[creator: AddressLike], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "allPresales"): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createLaunchDotFunPresale"
  ): TypedContractMethod<
    [_token: AddressLike, _options: LaunchDotFunPresale.PresaleOptionsStruct],
    [string],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "getPresalesByCreator"): TypedContractMethod<[creator: AddressLike], [string[]], "view">;

  getEvent(
    key: "LaunchDotFunPresaleCreated"
  ): TypedContractEvent<
    LaunchDotFunPresaleCreatedEvent.InputTuple,
    LaunchDotFunPresaleCreatedEvent.OutputTuple,
    LaunchDotFunPresaleCreatedEvent.OutputObject
  >;

  filters: {
    "LaunchDotFunPresaleCreated(address,address,address,address,address)": TypedContractEvent<
      LaunchDotFunPresaleCreatedEvent.InputTuple,
      LaunchDotFunPresaleCreatedEvent.OutputTuple,
      LaunchDotFunPresaleCreatedEvent.OutputObject
    >;
    LaunchDotFunPresaleCreated: TypedContractEvent<
      LaunchDotFunPresaleCreatedEvent.InputTuple,
      LaunchDotFunPresaleCreatedEvent.OutputTuple,
      LaunchDotFunPresaleCreatedEvent.OutputObject
    >;
  };
}
