/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LaunchDotFunTokenFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createToken" | "createdTokens" | "getTokensByCreator" | "tokenCreators"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TokenCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "createdTokens", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "getTokensByCreator", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "tokenCreators", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "createToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createdTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTokensByCreator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenCreators", data: BytesLike): Result;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    name: string,
    symbol: string,
    decimals: BigNumberish,
    totalSupply: BigNumberish,
    url: string,
    creator: AddressLike,
  ];
  export type OutputTuple = [
    tokenAddress: string,
    name: string,
    symbol: string,
    decimals: bigint,
    totalSupply: bigint,
    url: string,
    creator: string,
  ];
  export interface OutputObject {
    tokenAddress: string;
    name: string;
    symbol: string;
    decimals: bigint;
    totalSupply: bigint;
    url: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LaunchDotFunTokenFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LaunchDotFunTokenFactory;
  waitForDeployment(): Promise<this>;

  interface: LaunchDotFunTokenFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  createToken: TypedContractMethod<
    [name: string, symbol: string, decimals: BigNumberish, totalSupply: BigNumberish, url: string],
    [string],
    "nonpayable"
  >;

  createdTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getTokensByCreator: TypedContractMethod<[creator: AddressLike], [string[]], "view">;

  tokenCreators: TypedContractMethod<[token: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<
    [name: string, symbol: string, decimals: BigNumberish, totalSupply: BigNumberish, url: string],
    [string],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "createdTokens"): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(nameOrSignature: "getTokensByCreator"): TypedContractMethod<[creator: AddressLike], [string[]], "view">;
  getFunction(nameOrSignature: "tokenCreators"): TypedContractMethod<[token: AddressLike], [string], "view">;

  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;

  filters: {
    "TokenCreated(address,string,string,uint8,uint256,string,address)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
  };
}
